services:
  swarch-mo:
    build: .
    ports:
      - "8080:5000"   
    depends_on:
      - swarch-db
    restart: on-failure
    environment:
      - DATABASE_URL=mysql+mysqldb://root:123@swarch-db/swarch-db
    volumes:
      - .:/app

  swarch-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: swarch-db
    ports:
      - "3306:3306"
